Repository kube-reporting/hive, pull requests merged in 2020-08, with the labels that each got.

#44 Dockerfile: Update the maintainer label to use the team mailing list.
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel
  Dockerfile.rhel8
Labels: approved, lgtm

#47 Move to conditional build script
  Dockerfile.rhel8
  opt_maven_install.sh
Labels: approved, lgtm, ok-to-test

#46 Move to conditional build script
  Dockerfile
  Dockerfile.rhel8
  opt_maven_install.sh
Labels: approved, do-not-merge/work-in-progress

#48 Trigger manual rebuild of Hive after Hadoop image changes.
  Dockerfile.rhel8
Labels: approved

#49 Dockerfile: Add the summary label and update the description of the images.
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel
  Dockerfile.rhel8
Labels: approved, bugzilla/valid-bug, lgtm
